title: "SysAdminHelp"
author: "SysAdminHelp"
description: "A blog dedicated to the System Administration profession, made by a Junior System Administrator!"

email: "daniel.marshak@mail.com"
github_username: "SysAdminHelp"
linkedin_username: "daniel-marshak"

theme: "minima"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
