title: "SysAdminHelp"
author: "SysAdminHelp"
description: "A blog dedicated to the System Administration profession, made by a Junior System Administrator!"

email: "daniel.marshak@mail.com"
github_username: "SysAdminHelp"
linkedin_username: "daniel-marshak"

theme: "jekyll-theme-primer"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
