# Site settings
title: "SysAdminHelp"
author: "SysAdminHelp"
description: "Some short description of your blog can go here."

# Email / Social media usernames
email: "daniel.marshak@gmail.com"
github_username: "SysAdminHelp"
linkedin_username: "daniel-marshak"

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
kramdown:
  syntax_highlighter_opts:
    disable: true

# Navigation
nav_links:
  - title: Home
    url: "/"
  - title: About
    url: "/about/"

# Defaults
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
